### Introduction to NumPy

* Fast Mathematical Computational Library
* General purpose library using list available in Python is slow
* Homogenous data structure
* Specialized for doing mathematical computation
* Internally implemented using C - so fast
* High dimensional Computation
* Inbuilt utilities
* Mutabale

#### NumPy Creation
* From list
* zero init
* one init
* default value initialized
* range
* random

In [1]:
import numpy as np

#### From list

In [2]:
#initialize a as numpy array
a = np.array([2,3,4,4,5,1])

In [3]:
a

array([2, 3, 4, 4, 5, 1])

In [4]:
#add a data type to tthe given array
a = np.array([2,3,4,4,5,1], dtype=np.float32)

In [5]:
a.dtype

dtype('float32')

In [6]:
a

array([2., 3., 4., 4., 5., 1.], dtype=float32)

In [7]:
b = np.array(['hello', 'world', 'friends', 'iam', 'hamisu', 'muhammad'])

* The size of each element is decided by maximum size of word. 8 in this case

In [8]:
b.dtype

dtype('<U8')

#### Zero & One init

In [9]:
#Generates 4x4  numpy array which contains zeros elements
z = np.zeros((4,4))

In [10]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
a

array([2., 3., 4., 4., 5., 1.], dtype=float32)

##### zero_like
* create new data structure of same dimension/size as passed

In [12]:
np.zeros_like(a)

array([0., 0., 0., 0., 0., 0.], dtype=float32)

##### ones

In [15]:
#Generates 3x3 numpy array with 3D contains all 1s
a = np.ones((3,3,3))

##### ones_like

In [16]:
np.ones_like(a)

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

#### full
* Init all the contents with this

In [17]:
np.full( (6,6), 99)

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

In [18]:
np.full((3,3), 'hello')

array([['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello']], dtype='<U5')

In [19]:
np.full_like(a, 10)

array([[[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]],

       [[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]],

       [[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]]])

#### range
* Init a numpy array from start point to end point
* params - starting-point, ending-point & step size

In [20]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [21]:
np.arange(15,10,-1)

array([15, 14, 13, 12, 11])

#### random

In [22]:
#Generate 10 random numbers
d = np.random.rand(10)

In [23]:
d

array([0.07715183, 0.63784135, 0.26974667, 0.78511858, 0.27531062,
       0.56743954, 0.33975271, 0.93204133, 0.61817453, 0.26477907])

In [24]:
#Generates a 2x3 numpy array 
np.random.randn(2,3)

array([[ 0.10530056, -1.19429666,  0.12909744],
       [ 2.53256302, -1.79368764, -1.59177912]])

* int array between 5 & 10

In [25]:
#Generates 3x3 numpy array integer value from 5 to 10
np.random.randint(5,10,size=(3,3))

array([[9, 9, 9],
       [8, 5, 6],
       [7, 6, 9]])

##### shuffle
* randomizes the contents

In [26]:
np.random.shuffle(d)

In [27]:
d

array([0.78511858, 0.93204133, 0.33975271, 0.26974667, 0.56743954,
       0.26477907, 0.27531062, 0.63784135, 0.61817453, 0.07715183])

##### seed
* controls the output 
* using same seed, we will get same output

In [29]:
np.random.seed(1)
np.random.randint(5,10,size=(3,3))

array([[8, 9, 5],
       [6, 8, 5],
       [5, 6, 9]])

### Accessing elements

In [30]:
np.random.seed(10)
data = np.random.randint(2,20,size=(5,5))

In [31]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

#### Two ways to access single element

In [34]:
#first one 
data[2][1]

10

In [35]:
#Second one
data[2,1]

10

#### Accessing only the first row

In [36]:
data[1]

array([18, 19, 10, 11,  2])

#### Accessing first onwards all the rows

In [37]:
data[1:]

array([[18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

#### Accessing till row 2

In [39]:
data[:2]

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2]])

#### Column access

In [40]:
data[:,1:3]

array([[ 6, 17],
       [19, 10],
       [10,  6],
       [13, 13],
       [16, 19]])

* Question : Get slice containing 6,18,13,3

In [42]:
data[2:4, 2:4]

array([[ 6, 18],
       [13,  3]])

#### Shape, Size & Dimension
* These are not functions but attributes

Provide information on dimension

In [43]:
data.shape

(5, 5)

Total size of data

In [44]:
data.size

25

ndim - returns num of dimension, 2 in matrix, 3 in 

In [45]:
data.ndim

2

#### Reshaping data
* Changes shape & dimension of data but not size

In [46]:
a = np.array([1,2,3,4,5,6])

In [47]:
a.shape

(6,)

In [48]:
a.ndim

1

In [49]:
b = a.reshape((2,3))

In [50]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
b.ndim

2

In [52]:
b.shape

(2, 3)

In [53]:
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
b.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Adding one dim

In [55]:
a = np.array([1,2,3,4,5,6])

#### Adds one dimension 

In [56]:
a.reshape((a.shape[0],1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [57]:
a.shape

(6,)

#### Yet another way to add one more dimension 

In [58]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [59]:
data[:,np.newaxis]

array([[[11,  6, 17,  2, 19]],

       [[18, 19, 10, 11,  2]],

       [[12, 10,  6, 18,  6]],

       [[17, 13, 13,  3, 10]],

       [[ 6, 16, 19, 15,  7]]])

#### Convert data into 1-d of 25 elements

In [60]:
data.reshape(25)

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7])

In [61]:
data.reshape(*data.shape,1).shape

(5, 5, 1)

#### removal of dimension , converts into 1D data .i.e flattens it out

In [62]:
np.ravel(data)

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7])

### Concatination
* Combining data

#### Combining 1-D data

In [63]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [64]:
np.concatenate([x,y,x])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

#### Axis
* 0 - vertical
* 1 - horizontal

#### Combining 2D data
* by default axis zero

In [65]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [66]:

np.concatenate([data,data])

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [67]:
np.concatenate([data,data], axis=1)

array([[11,  6, 17,  2, 19, 11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2, 18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6, 12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10, 17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7,  6, 16, 19, 15,  7]])

#### append
* adds value at the end of the array

In [68]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [69]:
np.append(data, [1,2,3,4,5])

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7,  1,  2,  3,  4,  5])

In [70]:
np.append(data, [[1,2,3,4,5]], axis=0)

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [ 1,  2,  3,  4,  5]])

In [71]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

### horizontal stacking

In [72]:
np.hstack([data,data])

array([[11,  6, 17,  2, 19, 11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2, 18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6, 12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10, 17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7,  6, 16, 19, 15,  7]])

### vertical stacking

In [73]:
np.vstack([data,data])

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

#### Rules
* hstacking - num of rowst should be same 
* vstacking - num of cols should be same